#!/usr/bin/env python3
"""
cyberworld_report.py
====================
Generates HTML and Markdown reports for CyberWorld / FLLC activity
and pushes them to the Personfu/REPORTS repository.

Triggered by: .github/workflows/cyberworld-reports.yml
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests
from github import Github, GithubException


# ---------------------------------------------------------------------------
# Configuration (injected via GitHub Actions secrets / env vars)
# ---------------------------------------------------------------------------
GITHUB_TOKEN   = os.environ.get("GH_PAT") or os.environ.get("GITHUB_TOKEN", "")
SOURCE_REPO    = os.environ.get("SOURCE_REPO",  "Personfu/CYBERWORLDSOURCECODE")
REPORTS_REPO   = os.environ.get("REPORTS_REPO", "Personfu/REPORTS")
REPORT_BRANCH  = os.environ.get("REPORT_BRANCH", "main")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def now_utc() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _gh_client() -> Github:
    if not GITHUB_TOKEN:
        raise RuntimeError("GH_PAT / GITHUB_TOKEN environment variable is not set.")
    return Github(GITHUB_TOKEN)


# ---------------------------------------------------------------------------
# Data collection
# ---------------------------------------------------------------------------
def collect_repo_stats(gh: Github) -> dict:
    """Collect open PRs, issues, latest commits, and workflow runs."""
    repo = gh.get_repo(SOURCE_REPO)

    open_prs = [
        {
            "number": pr.number,
            "title":  pr.title,
            "state":  pr.state,
            "url":    pr.html_url,
            "author": pr.user.login,
            "created": str(pr.created_at),
        }
        for pr in repo.get_pulls(state="open")
    ]

    open_issues = [
        {
            "number": iss.number,
            "title":  iss.title,
            "url":    iss.html_url,
            "author": iss.user.login,
            "created": str(iss.created_at),
        }
        for iss in repo.get_issues(state="open")
        if iss.pull_request is None
    ]

    recent_commits = [
        {
            "sha":     c.sha[:7],
            "message": c.commit.message.split("\n")[0],
            "author":  c.commit.author.name,
            "date":    str(c.commit.author.date),
            "url":     c.html_url,
        }
        for c in repo.get_commits()[:10]
    ]

    workflow_runs: list[dict] = []
    try:
        for wf in repo.get_workflows():
            for run in wf.get_runs()[:3]:
                workflow_runs.append({
                    "workflow": wf.name,
                    "status":   run.status,
                    "conclusion": run.conclusion,
                    "run_number": run.run_number,
                    "url":      run.html_url,
                    "created":  str(run.created_at),
                })
    except GithubException:
        pass  # Workflow data may not be available in all contexts

    return {
        "generated_at": now_utc(),
        "source_repo":  SOURCE_REPO,
        "open_prs":     open_prs,
        "open_issues":  open_issues,
        "recent_commits": recent_commits,
        "workflow_runs":  workflow_runs,
    }


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------
MARKDOWN_TEMPLATE = """\
# 🌐 CyberWorld Automation Report

> **Generated:** {generated_at}  
> **Source:** [{source_repo}](https://github.com/{source_repo})

---

## 📋 Open Pull Requests ({pr_count})

{pr_table}

---

## 🐛 Open Issues ({issue_count})

{issue_table}

---

## 🔄 Recent Commits

{commit_table}

---

## ⚙️ Recent Workflow Runs

{workflow_table}

---
*Auto-generated by [cyberworld_report.py](https://github.com/{source_repo}/blob/main/automations/cyberworld_report.py)*
"""

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>CyberWorld Report — {generated_at}</title>
  <style>
    :root {{ --neon: #00ffcc; --bg: #050515; --card: #0d0d2b; --text: #c8fffe; }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: var(--bg); color: var(--text); font-family: 'Courier New', monospace;
            padding: 2rem; }}
    h1 {{ color: var(--neon); text-shadow: 0 0 12px var(--neon); margin-bottom: 1rem; }}
    h2 {{ color: #7aefff; margin: 1.5rem 0 .5rem; border-bottom: 1px solid #1a3a3a; padding-bottom: .3rem; }}
    table {{ width: 100%; border-collapse: collapse; margin-bottom: 1rem; }}
    th {{ background: #0a1a2a; color: var(--neon); padding: .5rem; text-align: left; }}
    td {{ padding: .4rem .5rem; border-bottom: 1px solid #112233; }}
    a {{ color: #00ffcc; }}
    .badge-open    {{ color: #00ff88; }}
    .badge-closed  {{ color: #ff4466; }}
    .badge-success {{ color: #00ff88; }}
    .badge-failure {{ color: #ff4466; }}
    .ts {{ color: #556677; font-size: .85em; }}
    footer {{ margin-top: 2rem; color: #334455; font-size: .85em; }}
  </style>
</head>
<body>
  <h1>🌐 CyberWorld Automation Report</h1>
  <p class="ts">Generated: {generated_at} | Source: <a href="https://github.com/{source_repo}">{source_repo}</a></p>

  <h2>📋 Open Pull Requests ({pr_count})</h2>
  {pr_html}

  <h2>🐛 Open Issues ({issue_count})</h2>
  {issue_html}

  <h2>🔄 Recent Commits</h2>
  {commit_html}

  <h2>⚙️ Recent Workflow Runs</h2>
  {workflow_html}

  <footer>Auto-generated by
    <a href="https://github.com/{source_repo}/blob/main/automations/cyberworld_report.py">cyberworld_report.py</a>
  </footer>
</body>
</html>
"""


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_None_\n"
    sep = " | ".join("---" for _ in headers)
    head = " | ".join(headers)
    lines = [f"| {head} |", f"| {sep} |"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines) + "\n"


def _html_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "<p><em>None</em></p>"
    th = "".join(f"<th>{h}</th>" for h in headers)
    body_rows = ""
    for row in rows:
        tds = "".join(f"<td>{c}</td>" for c in row)
        body_rows += f"<tr>{tds}</tr>"
    return f"<table><thead><tr>{th}</tr></thead><tbody>{body_rows}</tbody></table>"


def render_markdown(data: dict) -> str:
    pr_rows = [
        [f"[#{p['number']}]({p['url']})", p["title"][:60], p["author"], p["created"][:10]]
        for p in data["open_prs"]
    ]
    issue_rows = [
        [f"[#{i['number']}]({i['url']})", i["title"][:60], i["author"], i["created"][:10]]
        for i in data["open_issues"]
    ]
    commit_rows = [
        [f"[`{c['sha']}`]({c['url']})", c["message"][:60], c["author"], c["date"][:10]]
        for c in data["recent_commits"]
    ]
    wf_rows = [
        [w["workflow"], w["status"], w["conclusion"] or "-", f"[#{w['run_number']}]({w['url']})", w["created"][:10]]
        for w in data["workflow_runs"]
    ]

    return MARKDOWN_TEMPLATE.format(
        generated_at=data["generated_at"],
        source_repo=data["source_repo"],
        pr_count=len(pr_rows),
        pr_table=_md_table(["PR", "Title", "Author", "Created"], pr_rows),
        issue_count=len(issue_rows),
        issue_table=_md_table(["Issue", "Title", "Author", "Created"], issue_rows),
        commit_table=_md_table(["SHA", "Message", "Author", "Date"], commit_rows),
        workflow_table=_md_table(["Workflow", "Status", "Conclusion", "Run", "Date"], wf_rows),
    )


def render_html(data: dict) -> str:
    def link(url: str, label: str) -> str:
        return f'<a href="{url}">{label}</a>'

    pr_rows = [
        [link(p["url"], f"#{p['number']}"), p["title"][:60], p["author"], p["created"][:10]]
        for p in data["open_prs"]
    ]
    issue_rows = [
        [link(i["url"], f"#{i['number']}"), i["title"][:60], i["author"], i["created"][:10]]
        for i in data["open_issues"]
    ]
    commit_rows = [
        [link(c["url"], c["sha"]), c["message"][:60], c["author"], c["date"][:10]]
        for c in data["recent_commits"]
    ]
    wf_rows = [
        [w["workflow"], w["status"], w["conclusion"] or "-",
         link(w["url"], f"#{w['run_number']}"), w["created"][:10]]
        for w in data["workflow_runs"]
    ]

    return HTML_TEMPLATE.format(
        generated_at=data["generated_at"],
        source_repo=data["source_repo"],
        pr_count=len(pr_rows),
        pr_html=_html_table(["PR", "Title", "Author", "Created"], pr_rows),
        issue_count=len(issue_rows),
        issue_html=_html_table(["Issue", "Title", "Author", "Created"], issue_rows),
        commit_html=_html_table(["SHA", "Message", "Author", "Date"], commit_rows),
        workflow_html=_html_table(["Workflow", "Status", "Conclusion", "Run", "Date"], wf_rows),
    )


# ---------------------------------------------------------------------------
# Push to REPORTS repo
# ---------------------------------------------------------------------------
def push_report(gh: Github, md_content: str, html_content: str, json_data: dict) -> None:
    repo = gh.get_repo(REPORTS_REPO)
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    files = {
        "cyberworld/latest.md":               md_content,
        f"cyberworld/archive/{timestamp}.md": md_content,
        "cyberworld/latest.html":             html_content,
        "cyberworld/latest.json":             json.dumps(json_data, indent=2),
    }

    for path, content in files.items():
        commit_msg = f"chore(report): update CyberWorld report {timestamp}"
        encoded = content.encode("utf-8")
        try:
            existing = repo.get_contents(path, ref=REPORT_BRANCH)
            repo.update_file(path, commit_msg, encoded, existing.sha, branch=REPORT_BRANCH)
            print(f"  ✔ Updated {path}")
        except GithubException:
            repo.create_file(path, commit_msg, encoded, branch=REPORT_BRANCH)
            print(f"  ✔ Created {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    print("🌐 CyberWorld Report Generator")
    print(f"  Source  : {SOURCE_REPO}")
    print(f"  Reports : {REPORTS_REPO}")
    print()

    gh = _gh_client()

    print("📊 Collecting repository stats…")
    data = collect_repo_stats(gh)

    print("📝 Rendering reports…")
    md_report   = render_markdown(data)
    html_report = render_html(data)

    print("🚀 Pushing reports to Personfu/REPORTS…")
    push_report(gh, md_report, html_report, data)

    print("\n✅ Done!")


if __name__ == "__main__":
    main()
