#!/usr/bin/env python3
"""
sync_repos.py
=============
Synchronises assets and manifest data across CyberWorld / FLLC repositories
and generates an asset manifest pushed to Personfu/REPORTS.

Triggered by: .github/workflows/sync-repos.yml
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from github import Github, GithubException


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
GITHUB_TOKEN  = os.environ.get("GH_PAT") or os.environ.get("GITHUB_TOKEN", "")
REPORTS_REPO  = os.environ.get("REPORTS_REPO",  "Personfu/REPORTS")
REPORT_BRANCH = os.environ.get("REPORT_BRANCH", "main")

# Repositories included in the sync scope
SCOPE_REPOS: list[str] = [
    "Personfu/CYBERWORLDSOURCECODE",
    "Personfu/REPORTS",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def now_utc() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _gh() -> Github:
    if not GITHUB_TOKEN:
        raise RuntimeError("GH_PAT / GITHUB_TOKEN environment variable is not set.")
    return Github(GITHUB_TOKEN)


# ---------------------------------------------------------------------------
# Asset manifest generation
# ---------------------------------------------------------------------------
ASSET_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".svg",
    ".blend", ".fbx", ".obj",
    ".xcf", ".psd",
    ".mp3", ".wav", ".ogg",
    ".unity", ".prefab", ".asset",
    ".json", ".xml", ".csv",
}


def _is_asset(path: str) -> bool:
    return Path(path).suffix.lower() in ASSET_EXTENSIONS


def build_asset_manifest(gh: Github) -> dict[str, Any]:
    """Walk source repos and build a manifest of all tracked assets."""
    manifest: dict[str, Any] = {
        "generated_at": now_utc(),
        "repos": {},
    }

    for repo_name in SCOPE_REPOS:
        try:
            repo = gh.get_repo(repo_name)
            assets: list[dict] = []

            contents_queue = [repo.get_contents("")]
            while contents_queue:
                batch = contents_queue.pop()
                if not isinstance(batch, list):
                    batch = [batch]
                for item in batch:
                    if item.type == "dir":
                        contents_queue.append(repo.get_contents(item.path))
                    elif _is_asset(item.path):
                        assets.append({
                            "path":    item.path,
                            "sha":     item.sha,
                            "size":    item.size,
                            "url":     item.html_url,
                            "type":    Path(item.path).suffix.lower().lstrip("."),
                        })

            manifest["repos"][repo_name] = {
                "total_assets": len(assets),
                "assets": assets,
            }
            print(f"  ✔ {repo_name}: {len(assets)} assets indexed")

        except GithubException as exc:
            print(f"  ⚠ Could not access {repo_name}: {exc}", file=sys.stderr)
            manifest["repos"][repo_name] = {"error": str(exc)}

    return manifest


# ---------------------------------------------------------------------------
# Sync README / index across repos
# ---------------------------------------------------------------------------
def sync_readme_summary(gh: Github, manifest: dict) -> None:
    """Push a summary index to Personfu/REPORTS."""
    repo = gh.get_repo(REPORTS_REPO)
    ts   = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "# 🗂️ CyberWorld Asset & Repo Sync Report",
        "",
        f"> **Generated:** {manifest['generated_at']}",
        "",
        "## Repositories in Scope",
        "",
    ]

    for repo_name, info in manifest["repos"].items():
        if "error" in info:
            lines.append(f"- ❌ **{repo_name}** — sync error: {info['error']}")
        else:
            lines.append(f"- ✅ **[{repo_name}](https://github.com/{repo_name})** — {info['total_assets']} assets")

    lines += [
        "",
        "## Asset Manifest",
        "",
        f"- [latest.json](cyberworld/assets/latest.json)",
        f"- [archive/{ts}.json](cyberworld/assets/archive/{ts}.json)",
        "",
        "---",
        "*Auto-generated by [sync_repos.py]"
        f"(https://github.com/Personfu/CYBERWORLDSOURCECODE/blob/main/automations/sync_repos.py)*",
    ]

    md_content = "\n".join(lines)
    _upsert_file(repo, "cyberworld/sync-report.md", md_content, f"chore(sync): update sync report {ts}")


def _upsert_file(repo: Any, path: str, content: str, message: str) -> None:
    encoded = content.encode("utf-8")
    try:
        existing = repo.get_contents(path, ref=REPORT_BRANCH)
        repo.update_file(path, message, encoded, existing.sha, branch=REPORT_BRANCH)
        print(f"  ✔ Updated {path}")
    except GithubException:
        repo.create_file(path, message, encoded, branch=REPORT_BRANCH)
        print(f"  ✔ Created {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    print("🔄 CyberWorld Repo Sync & Asset Manifest Generator")
    print(f"  Reports repo: {REPORTS_REPO}")
    print(f"  Scope: {', '.join(SCOPE_REPOS)}")
    print()

    gh = _gh()

    print("📦 Building asset manifest…")
    manifest = build_asset_manifest(gh)

    print("\n🚀 Pushing to Personfu/REPORTS…")
    reports_repo = gh.get_repo(REPORTS_REPO)
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    commit_msg = f"chore(sync): asset manifest {ts}"

    _upsert_file(reports_repo, "cyberworld/assets/latest.json",
                 json.dumps(manifest, indent=2), commit_msg)
    _upsert_file(reports_repo, f"cyberworld/assets/archive/{ts}.json",
                 json.dumps(manifest, indent=2), commit_msg)

    sync_readme_summary(gh, manifest)

    print("\n✅ Sync complete!")


if __name__ == "__main__":
    main()
